### ISSUE TITLE
SendMsg waits forever, no errors.

### ISSUE THREAD

**Issue by kevinroleke** [strangelove-ventures/lens#172]
Hi.

I'm trying to use lens' SendMsg with wasmd. 

```go
msg, _ := json.Marshal(CW20Transfer{
      Data: CW20TransferData{
	      Amount: amount_to_send,
	      Recipient: address,
      },
})

req := &wasmdtypes.MsgExecuteContract{
      Sender: SrcWalletAddress,
      Contract: contract,
      Msg: msg,
}

res, err := chainClient.SendMsg(context.Background(), req)
fmt.Println("never gets here. the above line just waits forever without returning")
if err != nil {
      if res != nil {
	      return CosmosTXRespone{}, fmt.Errorf("failed to send")
      }
      return CosmosTXRespone{}, err
}
```

The RPC being used works. And I am able to send this exact message using wasmd CLI.

Any idea whats going on here/how to debug?

**Comment by jtieri** [comment]
Hmm it shouldn't hang forever. The default timeout is `10min` with the option to override it via your config, see:
https://github.com/strangelove-ventures/lens/blob/6b6dbf09127fcb5a85f3ee3257f254a3bce98f34/client/broadcast.go#L18-L43

I don't believe we have wired up the `AppModuleBasic` for `wasm` either though so there may be some issues around encoding/decoding wasm message types.

https://github.com/strangelove-ventures/lens/blob/6b6dbf09127fcb5a85f3ee3257f254a3bce98f34/client/config.go#L27-L49

Previously when I tried to add that in the past there was some contention between `wasm` and `ibc-go/v3` that caused issues but perhaps they have been solved by now. I'll take a look and try to get a PR opened real quick.

**Comment by kevinroleke** [comment]
Thanks for the PR @jtieri 

Sadly this did not fix the issue for me, but at least now I am getting the timeout message.

`%v timed out after: 600000000000; timed out after waiting for tx to get included in the block`

**Comment by jtieri** [comment]
> Thanks for the PR @jtieri
> 
> Sadly this did not fix the issue for me, but at least now I am getting the timeout message.
> 
> `%v timed out after: 600000000000; timed out after waiting for tx to get included in the block`

Would you mind sharing your config file? Default location is `~/.lens/config.yaml`

**Comment by kevinroleke** [comment]
> > Thanks for the PR @jtieri
> > Sadly this did not fix the issue for me, but at least now I am getting the timeout message.
> > `%v timed out after: 600000000000; timed out after waiting for tx to get included in the block`
> 
> Would you mind sharing your config file? Default location is `~/.lens/config.yaml`

It looks like I have no configuration for the chain I'm using in config.yaml. 

These are the settings I use in my program:
```go
chainConfig := lens.ChainClientConfig{
		Key:     configuration.COSMOS_SOURCEKEY,
		ChainID: configuration.COSMOS_CHAINID, // uni-3
		RPCAddr: configuration.COSMOS_RPC,
		AccountPrefix:  configuration.COSMOS_PREFIX, // juno
		KeyringBackend: configuration.COSMOS_KEYRINGBACKEND, // file
		GasAdjustment:  1.2,
		GasPrices:      "0.01" + configuration.COSMOS_UNIT, // ujuno
		KeyDirectory:   configuration.COSMOS_KEYDIR, // ~/.juno
		Debug:          true,
		Timeout:        "20s",
		OutputFormat:   "json",
		SignModeStr:    "direct",
		Modules:        lens.ModuleBasics,
	}
```

**Comment by kevinroleke** [comment]
Oops. Looks like it was just a typo in the unit. 

Should be "ujunox" instead of "ujuno"
